[package]
name = "GitTrial"
version = "0.1.0"
edition = "2024"

[dependencies]
tch = { version = "0.20.0", features = ["download-libtorch"] }
anyhow = "1.0.100"
flate2 = "1.1.2"
reqwest = "0.12.23"
tokio = { version = "1.47.1", features = ["rt", "rt-multi-thread", "macros"] }